version: "2.0"

stages:
- 前置检查
- 构建&发布到测试库
- 验包&确认
- 发布正式库前检查
- 发布正式库

jobs:
  单元测试:
    stage: 前置检查
    component: python-ut
    inputs:
      languageConfig:
        pythonVersion: "3.7.1"
    config:
      execute:
        isAllowSkip: true

  代码检查:
    stage: 前置检查
    component: python-sast
    inputs:
      excludes: # 选填项，排除哪些项不进行代码扫描
        - "**__init__.py**"
        - "**/tests/**"
        - ansible/*
        - config/*
        - "**config.py**"
      codePath: "./psmatch" # 选填项，选择扫描目录
    config:
      execute:
        timeout: 600 # 选填项，任务超时时间
        isAllowSkip: true
      afterExecute:
        checkRule:  # 选填项，卡点策略, 根据实际团队质量要求进行配置
          - ${{outputs.critical}} <= 30

  STC安全扫描:
    stage: 前置检查
    component: stc
    inputs:
      tenantName: null
    config:
      execute:
        isAllowSkip: false

  构建并发布到测试库:
    stage: 构建&发布到测试库
    id: build
    component: pypi-artifact-uploader
    inputs:
      registry: "https://artifacts.antgroup-inc.cn/artifact/repositories/simple-dev/" # 测试库地址
      workdir: . # pypi 工程目录，默认在此目录下进行 python -m build 并输出到 dist 目录, 详细可参考组件首页说明

  选择迁移制品:
    id: check
    stage: 发布正式库前检查
    component: artifact-transfer-check
    inputs:
      artifactsConfigs:
        - artifacts: ${{jobs.build.outputs.artifacts}}
          type: PYPI
          antArtifactRepo: simple

  同步至正式库:
    stage: 发布正式库
    component: ant-artifact-transfer
    inputs:
      transferArtifacts: ${{jobs.check.outputs.transferArtifacts}}
    config:
      beforeExecute:
        isAutoSkip: ${{jobs.check.outputs.selectedCount}} = 0
        confirm:
          buttonName: 确认发布正式库
          approvers:
          - yunjie.gyj # 具备发布角色的用户的域账号